spring.config.import=optional:file:.env[.properties]

spring.application.name=${APPLICATION_NAME:JobNet}
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017}
spring.data.mongodb.auto-index-creation=${MONGO_AUTO_INDEX_CREATION:true}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB

app.jwt.secret=${JWT_SECRET:jhguvvtjciou68ty7r6tydcv7i6uydf76ytfrdtcv7i6utj8i7uyo98i7uy}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:600000}
app.jwt.refresh-expiration-ms=${JWT_REFRESH_EXPIRATION_MS:604800000}
app.flask.base-url=${FLASK_HOSTED_URL:http://127.0.0.1:5000}
app.skills.client-id=${SKILLS_CLIENT_ID:}
app.skills.client-secret=${SKILLS_CLIENT_SECRET:}
app.skills.token-url=${SKILLS_TOKEN_URL:https://auth.emsicloud.com/connect/token}
app.skills.base-url=${SKILLS_BASE_URL:https://emsiservices.com/skills/versions/latest/skills}
app.skills.scope=${SKILLS_SCOPE:emsi_open}

